# Generated by Django 5.1.5 on 2025-02-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_parentprofile_user_remove_teacherprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="child_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="child_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="diplome",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="documents",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="account",
            name="proof_of_identity",
            field=models.FileField(
                blank=True, null=True, upload_to="proof_of_identity/"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
