# Generated by Django 5.1.5 on 2025-02-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_account_adresse_account_child_age_account_child_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
