# Generated by Django 5.1.5 on 2025-02-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customuser_role"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_groups", to="auth.group"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("directrice", "Directrice"),
                    ("educatrice", "Éducatrice"),
                    ("assistante", "Assistante"),
                    ("parent", "Parent"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True, related_name="customuser_permissions", to="auth.permission"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="presence",
            unique_together={("user", "date")},
        ),
    ]
