# Generated by Django 5.1.5 on 2025-02-07 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_customuser_groups_alter_customuser_role_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModelInViews",
        ),
    ]
