# Generated by Django 5.1.5 on 2025-02-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_delete_mymodelinviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProofOfIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="proof_of_identity/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="proof_of_identity",
        ),
        migrations.AddField(
            model_name="customuser",
            name="documents",
            field=models.ManyToManyField(blank=True, to="api.document"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="proof_of_identity",
            field=models.ManyToManyField(blank=True, to="api.proofofidentity"),
        ),
    ]
